//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOG_Visite
    {
        public long Visite_id { get; set; }
        public long Blog_Id { get; set; }
        public long Utilisateur_id { get; set; }
    
        public virtual BLOG_Blog BLOG_Blog { get; set; }
        public virtual UT_Utilisateur UT_Utilisateur { get; set; }
    }
}
