//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOG_Article
    {
        public BLOG_Article()
        {
            this.BLOG_Commentaire = new HashSet<BLOG_Commentaire>();
            this.BLOG_HashTagArticle = new HashSet<BLOG_HashTagArticle>();
            this.BLOG_Like = new HashSet<BLOG_Like>();
        }
    
        public long Article_id { get; set; }
        public long Blog_id { get; set; }
        public string TitreArticle { get; set; }
        public string ImageChemin { get; set; }
        public string ContenuArticle { get; set; }
        public Nullable<long> Evenement_id { get; set; }
        public System.DateTime DateCreation { get; set; }
        public Nullable<System.DateTime> DateModification { get; set; }
        public bool Actif { get; set; }
    
        public virtual BLOG_Blog BLOG_Blog { get; set; }
        public virtual EVE_Evenement EVE_Evenement { get; set; }
        public virtual ICollection<BLOG_Commentaire> BLOG_Commentaire { get; set; }
        public virtual ICollection<BLOG_HashTagArticle> BLOG_HashTagArticle { get; set; }
        public virtual ICollection<BLOG_Like> BLOG_Like { get; set; }
    }
}
