//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVE_Evenement
    {
        public EVE_Evenement()
        {
            this.BLOG_Article = new HashSet<BLOG_Article>();
            this.EVE_EvenementPhoto = new HashSet<EVE_EvenementPhoto>();
            this.EVE_HashTagEvenement = new HashSet<EVE_HashTagEvenement>();
            this.UT_Question = new HashSet<UT_Question>();
            this.UT_Utilisateur_Invite_Evenement = new HashSet<UT_Utilisateur_Invite_Evenement>();
            this.UT_Utilisateur_Participe_Evenement = new HashSet<UT_Utilisateur_Participe_Evenement>();
            this.UT_Utilisateur_Note_Evenement = new HashSet<UT_Utilisateur_Note_Evenement>();
        }
    
        public long Evenement_id { get; set; }
        public long Utilisateur_id { get; set; }
        public long LieuEvenement_id { get; set; }
        public long Categorie_id { get; set; }
        public System.DateTime DateEvenement { get; set; }
        public System.DateTime DateCreation { get; set; }
        public Nullable<System.DateTime> DateModification { get; set; }
        public System.DateTime DateFinInscription { get; set; }
        public string TitreEvenement { get; set; }
        public string DescriptionEvenement { get; set; }
        public Nullable<int> MinimumParticipant { get; set; }
        public Nullable<int> MaximumParticipant { get; set; }
        public string Statut { get; set; }
        public decimal Prix { get; set; }
        public bool Premium { get; set; }
        public Nullable<System.DateTime> DateMiseEnAvant { get; set; }
        public long Etat_id { get; set; }
        public string Nom { get; set; }
    
        public virtual ICollection<BLOG_Article> BLOG_Article { get; set; }
        public virtual EVE_Etat EVE_Etat { get; set; }
        public virtual UT_Categorie UT_Categorie { get; set; }
        public virtual ICollection<EVE_EvenementPhoto> EVE_EvenementPhoto { get; set; }
        public virtual EVE_LieuEvenement EVE_LieuEvenement { get; set; }
        public virtual UT_Utilisateur UT_Utilisateur { get; set; }
        public virtual ICollection<EVE_HashTagEvenement> EVE_HashTagEvenement { get; set; }
        public virtual ICollection<UT_Question> UT_Question { get; set; }
        public virtual ICollection<UT_Utilisateur_Invite_Evenement> UT_Utilisateur_Invite_Evenement { get; set; }
        public virtual ICollection<UT_Utilisateur_Participe_Evenement> UT_Utilisateur_Participe_Evenement { get; set; }
        public virtual ICollection<UT_Utilisateur_Note_Evenement> UT_Utilisateur_Note_Evenement { get; set; }
    }
}
