//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVE_LieuEvenement
    {
        public EVE_LieuEvenement()
        {
            this.EVE_Evenement = new HashSet<EVE_Evenement>();
        }
    
        public long LieuEvenement_id { get; set; }
        public string Ville { get; set; }
        public string CodePostale { get; set; }
        public string Adresse { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public string Pays { get; set; }
        public string Nom { get; set; }
    
        public virtual ICollection<EVE_Evenement> EVE_Evenement { get; set; }
    }
}
