//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOR_Topic
    {
        public FOR_Topic()
        {
            this.FOR_HashTagTopic = new HashSet<FOR_HashTagTopic>();
            this.FOR_Message = new HashSet<FOR_Message>();
        }
    
        public long Topic_id { get; set; }
        public long Sujet_id { get; set; }
        public string Nom { get; set; }
        public string DescriptifTopic { get; set; }
        public System.DateTime DateCreation { get; set; }
        public bool Resolu { get; set; }
        public long Utilisateur_id { get; set; }
    
        public virtual ICollection<FOR_HashTagTopic> FOR_HashTagTopic { get; set; }
        public virtual ICollection<FOR_Message> FOR_Message { get; set; }
        public virtual FOR_Sujet FOR_Sujet { get; set; }
        public virtual UT_Utilisateur UT_Utilisateur { get; set; }
    }
}
