//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOR_Sujet
    {
        public FOR_Sujet()
        {
            this.FOR_Topic = new HashSet<FOR_Topic>();
        }
    
        public long Sujet_id { get; set; }
        public long Forum_id { get; set; }
        public string Nom { get; set; }
    
        public virtual FOR_Forum FOR_Forum { get; set; }
        public virtual ICollection<FOR_Topic> FOR_Topic { get; set; }
    }
}
