//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOR_Forum
    {
        public FOR_Forum()
        {
            this.FOR_Sujet = new HashSet<FOR_Sujet>();
        }
    
        public long Forum_id { get; set; }
        public string Nom { get; set; }
        public string Url { get; set; }
    
        public virtual ICollection<FOR_Sujet> FOR_Sujet { get; set; }
    }
}
