//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class HC_Device
    {
        public HC_Device()
        {
            this.HC_Connexion = new HashSet<HC_Connexion>();
        }
    
        public long Device_id { get; set; }
        public string LibelleDevice { get; set; }
    
        public virtual ICollection<HC_Connexion> HC_Connexion { get; set; }
    }
}
