//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Site
    {
        public HR_Site()
        {
            this.HR_Historique = new HashSet<HR_Historique>();
            this.HR_Signaler = new HashSet<HR_Signaler>();
        }
    
        public long Site_id { get; set; }
        public string TypeSite { get; set; }
    
        public virtual ICollection<HR_Historique> HR_Historique { get; set; }
        public virtual ICollection<HR_Signaler> HR_Signaler { get; set; }
    }
}
