//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_Categorie
    {
        public UT_Categorie()
        {
            this.BLOG_Blog = new HashSet<BLOG_Blog>();
            this.EVE_Evenement = new HashSet<EVE_Evenement>();
            this.UT_Utilisateur_Aime_Categorie = new HashSet<UT_Utilisateur_Aime_Categorie>();
        }
    
        public long Categorie_id { get; set; }
        public string Libelle { get; set; }
    
        public virtual ICollection<BLOG_Blog> BLOG_Blog { get; set; }
        public virtual ICollection<EVE_Evenement> EVE_Evenement { get; set; }
        public virtual ICollection<UT_Utilisateur_Aime_Categorie> UT_Utilisateur_Aime_Categorie { get; set; }
    }
}
