//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_Utilisateur_Participe_Evenement
    {
        public long Participe_id { get; set; }
        public long Evenement_id { get; set; }
        public long Utilisateur_id { get; set; }
        public System.DateTime DateInscription { get; set; }
        public Nullable<System.DateTime> DateAnnulation { get; set; }
        public bool Annulation { get; set; }
    
        public virtual EVE_Evenement EVE_Evenement { get; set; }
        public virtual UT_Utilisateur UT_Utilisateur { get; set; }
    }
}
