//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_Utilisateur_Invite_Evenement
    {
        public long Invite_id { get; set; }
        public long Evenement_id { get; set; }
        public long UtilisateurPropose_id { get; set; }
        public long UtilisateurEstInvite_id { get; set; }
        public System.DateTime DateInvite { get; set; }
        public bool Repondu { get; set; }
    
        public virtual EVE_Evenement EVE_Evenement { get; set; }
        public virtual UT_Utilisateur UT_Utilisateur { get; set; }
        public virtual UT_Utilisateur UT_Utilisateur1 { get; set; }
    }
}
